name: Binary Ecstasy
favicon: null
layout_spectrum: 0.1612903
typography_spectrum: 0.5719978
title: Binary Ecstasy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0e0f7'
    - '#18221a'
    - '#8fbccf'
    - '#66554b'
    - '#fac49e'
  brandStrength: 0.6963949
  lightness: 0.4754215
  saturation: 0.1443224
  rhythmicContrast: 0.2641566
purpose: []
